# fly.toml app configuration file generated for synchronica on 2025-05-19T02:07:57-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'synchronica'
primary_region = 'dfw'

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[env]
  NODE_ENV = 'production'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
